### ISSUE TITLE
Slider jumps on mousedown

### ISSUE THREAD

**Issue by JesseHigson** [molovo/magic-roundabout#38]
The `transform` value on `.slideshow__slides` jumps when you interact with the slider.

![Screen Recording 2019-07-18 at 11 42 47](https://user-images.githubusercontent.com/12126304/61451750-0e123f00-a952-11e9-9de5-d91b7a49d4bd.gif)

**Comment by molovo** [comment]
Issue is resolved when `draggable: false`
